### ISSUE TITLE
Pictures not shown in Android client

### ISSUE THREAD

**Issue by poVoq** [ushahidi/platform-client#1243] opened 2018-08-24 17:22 UTC
### Expected behaviour
Like in the web-client submitted pictures in published survey responses should show in the Android App.

### Actual behaviour
Only a small "broken image" icon is shown (somewhat glitchy / blinking)

### Steps to reproduce the behaviour/error
Install own deployment from "production" branch (platform and client, pulled 2018-08-24), and connect with Ushahidi app from Playstore to it. Use app to submit a photo to this deployment. It can be seen in the web-client but not on any Android client.

**Comment by rowasc** [comment] 2018-09-05 13:55
Related https://github.com/ushahidi/platform-mobile/issues/181

**Comment by poVoq** [comment] 2018-09-05 14:39
Will that repository ever be opened to the public? Right now the link just results in a 404 error for me.

**Comment by bobinson** [comment] 2018-09-08 07:32
@rowasc - so the mobile-platform client code is not open source ?

**Comment by rowasc** [comment] 2018-09-27 18:35
@Eve-wanderi could you check my message above?

**Comment by poVoq** [comment] 2018-09-27 18:44
Just out of interest: am I guessing right that the mobile app is the regular web client + Cordova and a wrapper to allow selecting multiple deployments? That seems very little to keep closed, so it would be really nice if Ushahidi would be also opening their Android app :) Of course totally up to you.

**Comment by joelaldor** [comment] 2018-10-04 05:56
Any updates about this bug? I also seem to encounter this error when I post a survey response with an attached image on my Android app. Only that the image doesn't show **on both** the android app and the web app.

**Comment by rowasc** [comment] 2018-10-10 03:58
@joelaldor Could you confirm the android app version you are using, and if you are using a self hosted or ushahidi.io deployment? I was able to see my uploaded images both in the web client and the mobile android app right now (with the latest android version that went out a couple days ago) .

**Comment by rowasc** [comment] 2018-10-19 20:41
Closing .Cannot reproduce after last version went live

**Closed by rowasc** 2018-10-19 20:41 UTC
Labels: Bug, Mobile
