### ISSUE TITLE
The drop down menu of popup window performs incorrectly

### ISSUE THREAD

**Issue by yuchenglin** [ushahidi/platform-client#353] opened 2016-10-03 12:45 UTC
### Expected behaviour
The drop down menu would appear as a upper layer on the popup window

### Actual behaviour
Look like a sublayer in the popup window. Some buttons cannot be reached when the window is too small
![screen shot 2016-10-03 at 8 37 57 pm](https://cloud.githubusercontent.com/assets/5432898/19037672/04baf28c-89aa-11e6-9b1e-08525e5cd6fb.png)

### Steps to reproduce the behaviour/error
Tap a marker on map view

**Comment by jshorland** [comment] 2016-10-03 21:36
Hey @brandonrosage and @middle8media this looks like a design bug. Can one of you either fix, or hand it back to me if problem with pattern implementation?

**Comment by brandonrosage** [comment] 2016-10-04 14:35
@yuchenglin Any chance you can point us to your deployment, as well as the browser, browser version, and operating system you're experiencing this bug in?

On my end, I"m unable to replicate this bug. I see this:

![postcard](https://cloud.githubusercontent.com/assets/1136279/19078468/d78bec5a-8a15-11e6-989f-cc08e6a4091e.png)

**Comment by yuchenglin** [comment] 2016-10-05 06:05
@brandonrosage It breaks on both up-to-date chrome and safari. My OS is OSX 10.11.6. 
This bug is on my ubuntu server and also my [heroku deployment](https://cross-platform-client.herokuapp.com) (deploy from the latest develop branch).

**Comment by brandonrosage** [comment] 2016-10-26 21:12
I've patched this using CSS in the PL's `develop` branch and published to npm. It's ready to go.

We'll improve upon it with upcoming "free-form surveys" and how they improve "postcards."

**Comment by jshorland** [comment] 2016-10-27 14:14
Do I need to test this in our develop branch @brandonrosage ?

**Comment by brandonrosage** [comment] 2016-10-27 14:37
@jshorland We need someone to bring the PL's `develop` CSS into the client (if it's not already) and push to qa.ushahididev.com to test.

**Comment by willdoran** [comment] 2016-10-27 22:14
@brandonrosage I'm using 3.6.1-pre.6, is that correct?
The issue is still occurring for me. Is there a way to check I have the correct changes?

**Comment by rjmackay** [comment] 2016-10-28 03:01
This actually look ok on qa.ushahididev.com .. maybe you just had cached CSS locally?
https://www.dropbox.com/s/7cyrrwpkb7ejv6j/Screenshot%202016-10-28%2016.01.10.png?dl=0

**Comment by jshorland** [comment] 2016-10-28 17:20
PASSES! moving to waiting to deploy

**Closed** 2016-10-28 19:55 UTC
Labels: P0 - Unbreak now!
