### ISSUE TITLE
 The map does not appear when I first log in, but It appears after I reload the page

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform-client#765] opened 2017-09-27 21:30 UTC
### Expected behaviour
When I log in, in the views/map path, I see the map.
### Actual behaviour
The map does not appear when I first log in, it's an empty grey box until I reload the page. 

### Steps to reproduce the behaviour/error

- Load any deployment, ie: https://rominaushahidi.ushahidi.io/views/map.
- Login
- You will see a blank grey rectangle where the map should be.

**Comment by rowasc** [comment] 2017-09-27 21:32
@jshorland Jess, I found this. Not sure what to rank it, or why I didn't notice it before.

**Comment by willdoran** [comment] 2017-09-28 20:05
@Angamanga I think there is an issue caused by the No UI change for Diego. 
The problem occurs between these two commits. 

Could you test it out and look at patching it for Master? We can then back port that fix to Develop.

The issue seems like it's related to the class being applied to the map <div>

<div id="map" class="map" ng-class="getUIClass()" ></div>

**Comment by Angamanga** [comment] 2017-10-06 07:39
Closing, fixed in https://github.com/ushahidi/platform-client/commit/6b821003c06ed385aaa8b90a3de8ec35baf58500 and pushed to production

**Closed by Angamanga** 2017-10-06 07:39 UTC
Labels: P0 - Unbreak now!
